const QUERY_KEY_ATTRACTION = {
  GET_ALL: "GET_ALL_ATTRACTION",
  GET_FILTER: "GET_ALL_ATTRACTION_FILTER",
  GET_ALL_TRENDING: "GET_ALL_ATTRACTION_TRENDING",
  GET_NUMBEROFTICKETS: "GET_NUMBEROFTICKETS",
};
export default QUERY_KEY_ATTRACTION;
