const QUERY_KEY_BLOG = {
  GET_ALL: "GET_ALL_BLOG",
  GET_ALL_TRENDING: "GET_ALL_BLOG_TRENDING",
  GET_ALL_RELATE: "GET_ALL_BLOG_RELATE",
  GET_DETAIL_BLOG: "GET_DETAIL_BLOG",
};
export default QUERY_KEY_BLOG;
