const QUERY_KEY_HOTEL = {
  GET_ALL: "GET_ALL_HOTEL",
  GET_FILTER: "GET_ALL_HOTEL_FILTER",
  GET_LIST_ROOM_HOTEL: "GET_LIST_ROOM_HOTEL",
  GET_ALL_TRENDING: "GET_ALL_HOTEL_TRENDING",
  GET_ALL_BOOKED: "GET_ALL_BOOKED",
};
export default QUERY_KEY_HOTEL;
